name: Martin Mocko's personal webpage
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

collections:
  wpub:
    output: true
    permalink: /wpub/:path/


twitter_username: theruby__
github_username:  zerodayexploit
mail: martin.mocko1@gmail.com